image: docker:git

##### available pipline stages
stages:
  - build
##############################################################


##### build docker image job template
.job_template: &job_definition
  variables:
    IMAGE_FQDN: "$GV_REGISTRY_ADDRESS/$GV_REGISTRY_NAMESPACE/$CI_PROJECT_NAME:latest"
  script:
    - echo $GV_REGISTRY_PASSWORD | docker login -u $GV_REGISTRY_USERNAME --password-stdin $GV_REGISTRY_ADDRESS
    - if ! docker pull $IMAGE_FQDN; then docker pull $GV_REGISTRY_ADDRESS/$GV_REGISTRY_NAMESPACE/$CI_PROJECT_NAME:master || true; fi
    - docker build -t $IMAGE_FQDN .

  tags:
    - run01_docker

 ##############################################################
 #   - docker push $IMAGE_FQDN


##### build and push docker images to mtr registry
#Access to nexus is required to store there binary files
build_docker:
  <<: *job_definition
  stage: build
##############################################################
